# Generated by Django 4.2.6 on 2023-11-15 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_rename_receiver_privatemessage_recipient_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='developerprofile',
            name='skills_level_1',
        ),
        migrations.RemoveField(
            model_name='developerprofile',
            name='skills_level_2',
        ),
        migrations.DeleteModel(
            name='Skill',
        ),
        migrations.AddField(
            model_name='developerprofile',
            name='skills_level_1',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='developerprofile',
            name='skills_level_2',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
