# Generated by Django 4.2.6 on 2023-12-07 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_developerprofile_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developerprofile',
            name='portfolio_url',
            field=models.URLField(blank=True, default='', null=True),
        ),
    ]
