# Generated by Django 4.2.6 on 2023-11-14 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_developerprofile_available_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developerprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
