# Generated by Django 4.2.6 on 2023-11-14 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_developerprofile_skills_level_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='developerprofile',
            name='avatarPreview',
            field=models.TextField(blank=True, null=True),
        ),
    ]
