# Generated by Django 4.2.6 on 2023-11-14 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_developerprofile_avatarpreview'),
    ]

    operations = [
        migrations.RenameField(
            model_name='privatemessage',
            old_name='receiver',
            new_name='recipient',
        ),
        migrations.RemoveField(
            model_name='developerprofile',
            name='avatarPreview',
        ),
    ]
