# Generated by Django 4.2.6 on 2023-11-15 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_developerprofile_skills_level_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='developerprofile',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
