# Generated by Django 4.2.6 on 2023-11-29 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_remove_project_url_project_repo_url_project_site_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='developerprofile',
            name='skills_1',
            field=models.ManyToManyField(blank=True, related_name='skills_1', to='api.skill'),
        ),
        migrations.AddField(
            model_name='developerprofile',
            name='skills_2',
            field=models.ManyToManyField(blank=True, related_name='skills_2', to='api.skill'),
        ),
    ]
