# Generated by Django 4.2.6 on 2023-11-30 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_skill_developerprofile_skills_1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='developerprofile',
            name='skills_level_1',
        ),
        migrations.RemoveField(
            model_name='developerprofile',
            name='skills_level_2',
        ),
        migrations.AlterField(
            model_name='developerreview',
            name='rating',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
