# Generated by Django 4.2.6 on 2023-12-06 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_privatemessage_is_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='developerprofile',
            name='username',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
