# Generated by Django 4.2.6 on 2023-12-07 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_alter_developerprofile_portfolio_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developerprofile',
            name='portfolio_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
