# Generated by Django 4.2.6 on 2023-12-18 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_alter_developerprofile_portfolio_url'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProjectReview',
        ),
    ]
